# Taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"

# Brews
brew 'awscli'
brew 'awslogs'
brew 'coreutils'
brew 'dive' #docker image layer explorer
brew 'findutils'
brew 'git'
brew 'git-lfs'
# brew 'gnu-tar', args: ["with-default-names"]
# brew 'gnu-sed', args: ["with-default-names"]
brew 'go'
brew 'gpg'
# brew 'grep', args: ["with-default-names"]
brew 'jq' # JSON for bash
brew 'kubectl'
brew 'kubectx'
brew 'kubernetes-helm'
brew 'less'
brew 'mas'
brew 'node'
brew 'postgresql'
brew 'pv' # Copy progress tool
brew 'python'
# brew 'reattach-to-user-namespace' # TMUX patch for fixing copy/paste on macos
brew 'screen'
brew 'stress'
brew 'tfenv'
brew 'tflint'
brew 'trash'
brew 'tree'
brew 'unzip'
brew 'vim'
brew 'watch'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

# Casks
cask 'alfred'
cask 'brooklyn'
cask 'discord'
cask 'docker'
cask 'gimp'
cask 'google-chrome'
cask 'google-cloud-sdk'
cask 'iterm2'
cask 'muzzle' # auto-enable do not disturb on screenshares
cask 'slack'
cask 'spotify'
cask 'steermouse' # Better than usb overdrive
cask 'visual-studio-code'
cask 'vlc'

# App Store Apps
mas 'Xcode', id: 497799835