# Brews
brew 'bash'
brew 'docker'
brew 'git'
brew 'imagemagick'
brew 'mas'
brew 'maven'
brew 'node'
brew 'ruby'
brew 'screen'
brew 'sqlite'
brew 'wget'

# Casks
cask 'chefdk'
cask 'deathtodsstore'
cask 'dropbox'
cask 'firefox'
cask 'gimp'
cask 'google-chrome'
cask 'jetbrains-toolbox'
cask 'magicprefs' #Magic mouse fix
cask 'meld'
cask 'pgadmin4'
cask 'private-internet-access'
cask 'slack'
cask 'steam'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'

# App Store Apps
mas 'HyperDock', id: 449830122
mas 'Xcode', id: 497799835
