# Brews
brew 'bash'
brew 'docker'
brew 'git'
brew 'imagemagick'
brew 'mas'
brew 'maven'

# Casks
cask 'chefdk'
cask 'dropbox'
cask 'gimp'
cask 'magicprefs' #Magic mouse fix
cask 'meld'
cask 'vagrant'

# App Store Apps
mas 'HyperDock', id: 449830122
mas 'Xcode', id: 497799835
