# Taps
tap "caskroom/cask"

# Brews
brew 'awscli'
brew 'bash'
brew 'bash-completion'
brew 'git'
brew 'git-lfs'
brew 'gnupg'
brew 'gnupg2'
brew 'mas'
brew 'node'
brew 'python'
brew 'python3'
brew 'ruby'
brew 'screen'
brew 'sqlite'
brew 'stress'
brew 'wget'
brew 'zsh'
brew 'zsh-completions'

# Casks
cask 'alfred'
cask 'atom'
cask 'aws-vault'
cask 'chefdk'
cask 'deathtodsstore'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'gimp'
cask 'google-chrome'
cask 'iterm2'
cask 'jetbrains-toolbox'
cask 'magicprefs' #Magic mouse fix
cask 'meld'
cask 'pgadmin4'
cask 'pritunl'
cask 'private-internet-access'
cask 'slack'
cask 'spotify'
cask 'steam'
cask 'vagrant'
cask 'virtualbox'
cask 'vlc'

# App Store Apps
mas 'HyperDock', id: 449830122
mas 'LastPass', id: 926036361
mas 'Microsoft Remote Desktop', id: 1295203466
mas 'PiPifier', id: 1160374471 # Add pip button to safari
mas 'Xcode', id: 497799835
